data:
  data_type: train
  # 训练语言模型的数据，结构为： pinyin 汉字
  text_path: data/text_lm.txt
  batch_size: 2
  # 训练数据的大小，当val为False时训练数据为上面整个数据集。
  data_length: False
  pny_vocab_file: False
  han_vocab_file: False
model:
  num_heads: 8
  num_blocks: 6
  input_vocab_size: False
  label_vocab_size: False
  max_length: 100
  hidden_units: 512
  dropout_rate: 0.2
  lr: 0.0001
  is_training: True
train:
  epochs: 10
  retrain_dir: False
  save_path: logs_lm
